{% set name = "ipyvuetify" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 818e8674911ce4292724873d65f540c838a9681f6910cb9709bb6f93020e55a3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - ipywidgets >=7.0.0

test:
  imports:
    - ipyvuetify

about:
  home: http://github.com/mariobuikhuizen/ipyvuetify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Jupyter widgets based on vuetify UI components'

  description: |
    Jupyter widgets based on vuetify UI components  <https://vuetifyjs.com> which implement Google's 
    Material Design Spec <https://material.io/> with the Vue.js framework <https://vuejs.org/>.
  dev_url: http://github.com/mariobuikhuizen/ipyvuetify

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - maartenbreddels
