{% set name = "ipyvuetify" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87dee6aaadf316ee27ed89a79b3d3c3f5e0f2e5b638da0681736048532545ac1

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.0.0
    - ipyvue >=1.5,<2

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipyvuetify

about:
  home: http://github.com/mariobuikhuizen/ipyvuetify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter widgets based on vuetify UI components

  description: |
    Jupyter widgets based on vuetify UI components  <https://vuetifyjs.com> which implement Google's 
    Material Design Spec <https://material.io/> with the Vue.js framework <https://vuejs.org/>.
  dev_url: http://github.com/mariobuikhuizen/ipyvuetify

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - maartenbreddels
